[theme]
base = "dark"
primaryColor = "#34D399"
backgroundColor = "#090A0A"
secondaryBackgroundColor = "#111413"
textColor = "#F4F4F5"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
